### ISSUE TITLE
dd

### ISSUE THREAD

**Issue by mattdell** [realriot/ff4d#8]
Any idea why I can't use the dd command with ff4d?

I have ff4d running in a folder called dropbox. This is my command:

```
sudo dd if=/dev/xvda1 of=/home/ubuntu/matt/ff4d/dropbox/Backups/
```

And this is the error I get:

```
dd: failed to open ‘/home/ubuntu/matt/ff4d/dropbox/Backups/’: Permission denied
```

Any (safe) way around this?

**Comment by posita** [comment]
This is the correct (and safe) behavior for `dd`. From `man dd`:

```
...
     The dd utility copies the standard input to the standard output.  Input
     data is read and written in 512-byte blocks.  If input reads are short,
     input from multiple reads are aggregated to form the output block.  When
     finished, dd displays the number of complete and partial input and output
     blocks and truncated input records to the standard error output.
...
     of=file  Write output to file instead of the standard output.  Any regu-
              lar output file is truncated unless the notrunc conversion value
              is specified.  If an initial portion of the output file is
              seeked past (see the oseek operand), the output file is trun-
              cated at that point.
...
```

It looks like your `of` argument (`/home/ubuntu/matt/ff4d/dropbox/Backups/`) is a ***directory***, not a file or block device.

What did you expect your command to do? If you expected it to make a copy of your Xen disk image, you need to give a path to a file or block device (and you probably want to `umount` the disk first within your Xen virtual machine, otherwise you're likely going to have inconsistencies, but I don't know how Xen devices work, so you'll likely need to research this more). If you expected it to make a copy of your file hierarchy, `dd` is the wrong tool (try researching `rsync`).

Either way, this has nothing to do with `ff4d`. Please close this issue.
